name: the_movie_list_flutter
description: The Movie List written in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  tuple: ^1.0.3

  build_runner: ^1.0.0

  cupertino_icons: ^0.1.2

  flutter_spinkit: ^4.1.1

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  flutter_bloc: ^3.0.0

  equatable: ^0.6.1

  sqflite: ^1.1.7+2

  http: ^0.12.0+2

  inject:
    git:
      url: https://github.com/lvlrSajjad/inject.dart
      path: package/inject

dev_dependencies:
  flutter_test:
    sdk: flutter
  inject_generator:
    git:
      url: https://github.com/lvlrSajjad/inject.dart
      path: package/inject_generator


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
